SELECT * FROM SESSION_PRIVS;

SELECT * FROM USER_TABLES;

SELECT * FROM USER_TAB_PRIVS_RECD;

SELECT * FROM USER_COL_PRIVS_RECD;

SELECT * FROM USER_TAB_PRIVS_MADE;

SELECT * FROM USER_COL_PRIVS_MADE;

SELECT * FROM ROLE_SYS_PRIVS;

SELECT * FROM ROLE_ROLE_PRIVS;

SELECT * FROM ROLE_TAB_PRIVS;

SELECT * FROM USER_ROLE_PRIVS;

SELECT * FROM USER_SYS_PRIVS;

SELECT * FROM USER_USERS;

SET SERVEROUTPUT ON
BEGIN
DBMS_OUTPUT.PUT_LINE('MY FIRST');
END;
CREATE ROLE YYY;