SELECT * FROM SESSION_PRIVS
GRANT SELECT ON Ahmed.XX_EMP TO HR
REVOKE SELECT ON Ahmed.XX_EMP FROM HR
REVOKE All on HR.EMP from Ahmed
REVOKE ALL ON DBMS_STATS FROM HR
SHOW USER

CREATE ROLE MANAGER;

GRANT CREATE TABLE, CREATE SESSION, CREATE VIEW TO MANAGER
SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE = 'MANAGER'

GRANT MANAGER TO Ahmed

SELECT * FROM USER_RECYCLEBIN
SHOW con_name
select name from v$active_services;
select instance_name from v$instance;
CREATE PLUGGABLE DATABASE salespdb ADMIN USER hr IDENTIFIED BY hr;
create pluggable database PDBORCL admin user hr identified by hr
DROP USER Ahmed CASCADE
CREATE USER Ahmed IDENTIFIED BY ahmed
GRANT CREATE SESSION TO Ahmed
GRANT UNLIMITED TABLESPACE, CREATE TABLE TO HR WITH ADMIN OPTION
GRANT ALL PRIVILEGES TO HR
ALTER SESSION SET CONTAINER = XEPDB1
drop user hr CASCADE
show con_name
CREATE USER hme IDENTIFIED BY hme DEFAULT TABLESPACE USERS QUOTA 5M ON USERS
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO hme