SELECT * FROM SESSION_PRIVS
GRANT SELECT ON Ahmed.XX_EMP TO HR
REVOKE SELECT ON Ahmed.XX_EMP FROM HR
REVOKE All on HR.EMP from Ahmed
REVOKE ALL ON DBMS_STATS FROM HR
SHOW USER

CREATE ROLE MANAGER;

GRANT CREATE TABLE, CREATE SESSION, CREATE VIEW TO MANAGER
SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE = 'MANAGER'

GRANT MANAGER TO Ahmed

SELECT * FROM USER_RECYCLEBIN
SHOW con_name
select name from v$active_services;
select instance_name from v$instance;
CREATE PLUGGABLE DATABASE salespdb ADMIN USER hr IDENTIFIED BY hr;
create pluggable database PDBORCL admin user hr identified by hr
DROP USER Ahmed CASCADE
CREATE USER Ahmed IDENTIFIED BY ahmed
GRANT CREATE SESSION TO Ahmed
GRANT UNLIMITED TABLESPACE, CREATE TABLE TO HR WITH ADMIN OPTION
GRANT ALL PRIVILEGES TO HR
drop user hr CASCADE
show con_name
CREATE USER hme IDENTIFIED BY hme DEFAULT TABLESPACE USERS QUOTA 5M ON USERS
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO hme
GRANT CREATE PROCEDURE TO hme
CREATE ROLE SSS;
GRANT CREATE ROLE TO XYZ
CREATE ROLE XYZ;
CREATE ROLE XXX;
GRANT XXX TO XYZ;
GRANT XYZ TO HR;
DROP ROLE XYZ;
CREATE USER DN IDENTIFIED BY 123 QUOTA 5M ON USERS ACCOUNT LOCK PASSWORD EXPIRE
GRANT UNLIMITED TABLESPACE TO DN
REVOKE UNLIMITED TABLESPACE 
ALTER USER DN ACCOUNT UNLOCK IDENTIFIED BY 321
DROP USER DN CASCADE CONSTRAINTS
ALTER SESSION SET CONTAINER = XEPDB1
GRANT EXECUTE ON 
GRANT CREATE TRIGGER TO HME
CREATE DIRECTORY DIR AS 'E:\Documents\GitHub\A2D\Oracle';
GRANT READ, WRITE ON DIRECTORY DIR TO HR
DROP DIRECTORY DIR
DECLARE
FIL UTL_FILE.FILE_TYPE;
BEGIN
FIL := UTL_FILE.FOPEN('DIR', 'myfile.txt', 'A');
FOR I IN 1..5 LOOP
UTL_FILE.PUT_LINE(FIL, 'HELLO AHMED');
END LOOP;
UTL_FILE.FCLOSE(FIL);
END;

SET SERVEROUTPUT ON
DECLARE
FIL UTL_FILE.FILE_TYPE;
TEXT VARCHAR2(100); I NUMBER := 1;
BEGIN
FIL := UTL_FILE.FOPEN('DIR', 'myfile.txt', 'R');
LOOP
UTL_FILE.GET_LINE(FIL, TEXT);
I := I + 1;
IF I = 5 THEN
TEXT := NULL;
FOR I IN 1..4 LOOP
UTL_FILE.GET_LINE(FIL, TEXT);
DBMS_OUTPUT.PUT_LINE(TEXT);
END LOOP;
END IF;
END LOOP;
EXCEPTION WHEN NO_DATA_FOUND THEN
UTL_FILE.FCLOSE(FIL);
END;
CREATE ROLE ROLEAHMED;
GRANT CREATE SESSION TO ROLEAHMED
GRANT ALTER ON HR.EMP TO ROLEAHMED
DROP ROLE ROLEAHMED
alter session set "_ORACLE_SCRIPT"=true;  
CREATE PROFILE PRONAME LIMIT
SESSION_PER_USER 5
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME 6
PASSWORD_LOCK_TIME 6;
ALTER SESSION SET CONTAINER = XEPDB1
CREATE USER Mosque IDENTIFIED BY 123
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO Mosque
GRANT CREATE VIEW TO Mosque