//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hire_Me
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public decimal ID_ADMIN { get; set; }
        public string ADMIN_FIRST_NAME { get; set; }
        public string ADMIN_LAST_NAME { get; set; }
        public string ADMIN_FATHER_NAME { get; set; }
        public string ADMIN_EMAIL { get; set; }
        public string ADMIN_PASSWORD { get; set; }
    }
}
